version: '3'
services:
  nginx:
    image: bancamarchatm
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./data/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/www:/var/www/certbot/:r
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./data/certbot/www/:/var/www/certbot/:rw
      - ./data/certbot/conf/:/etc/letsencrypt/:rw
#https://mindsers.blog/post/https-using-nginx-certbot-docker/
#https://nkpremices.com/dynamically-set-angular-env-variables-in-docker/